### PR TITLE
Allow disabling of CRC verification

### PR DESCRIPTION
**Pull request by sk1p**
See #10 for details.

### CODE REVIEW

**Comment by martindurant** [comment]
Seems very reasonable.
You have tested this with hdfs3? Can you turn it off using 
`hdfs = HDFSFileSystem(..., pars={'input.read.default.verify': 'false'})`

I'd like to see cumbersome syntax above replaced by `crc=True|False` in the constructor, but that is just a simple change on the hdfs side.

**Comment by sk1p** [comment]
> You have tested this with hdfs3? Can you turn it off using [...]

Yes, [that's the way I tested it.](https://github.com/LiberTEM/LiberTEM/blob/master/benchmarks/hdfs/bench_buffering.py#L104)

> I'd like to see cumbersome syntax above replaced by crc=True|False in the constructor, but that is just a simple change on the hdfs side.

I agree, a pythonic `crc` kwarg is nice!

**Comment by martindurant** [comment]
`pars=defaultconfig` - ok, actually worked out what you were doing :)
This PR looks ready, was there anything more to add?

**Comment by sk1p** [comment]
> anything more to add?

Don't think so - btw. my C++ is a bit rusty, does the change in Hdfs.cpp look alright? It's mostly copy-paste from InputStreamImpl...

**Comment by martindurant** [comment]
I am surprised that you cannot do `fs->getFilesystem().getConf()->getEnableVerify()` without the intermediate `conf` variable, but my c++ must be lesser than just about anyone else I could care to ask.
If the build works and tests pass both with and without the parameter, then all is good.

**Comment by sk1p** [comment]
Tests - that's a good point. Unfortunately, ``make unittest`` doesn't work for me out of the box. I'll open a new ticket for that.

**Comment by martindurant** [comment]
You need gtest and gmock in addition to the code. They are not listed as requirements since they are only needed for tests.
I actually suggest you test by running pytest on hdfs3 with your build installed.

**Comment by sk1p** [comment]
gtest and gmock are installed - I get errors like this:

```
/home/alex/source/git/libhdfs3-downstream/libhdfs3/test/unit/TestLeaseRenewer.cpp: In member function ‘virtual void TestRenewer_Renew_Test::TestBody()’:
/home/alex/source/git/libhdfs3-downstream/libhdfs3/test/unit/TestLeaseRenewer.cpp:32:72: error: invalid new-expression of abstract class type ‘MockFileSystemInter’
     shared_ptr<MockFileSystemInter> filesystem(new MockFileSystemInter());
                                                                        ^
In file included from /home/alex/source/git/libhdfs3-downstream/libhdfs3/test/unit/TestLeaseRenewer.cpp:26:0:
/home/alex/source/git/libhdfs3-downstream/libhdfs3/mock/MockFileSystemInter.h:45:7: note:   because the following virtual functions are pure within ‘MockFileSystemInter’:
 class MockFileSystemInter: public Hdfs::Internal::FileSystemInter {
       ^~~~~~~~~~~~~~~~~~~
In file included from /home/alex/source/git/libhdfs3-downstream/libhdfs3/mock/MockFileSystemInter.h:30:0,
                 from /home/alex/source/git/libhdfs3-downstream/libhdfs3/test/unit/TestLeaseRenewer.cpp:26:
/home/alex/source/git/libhdfs3-downstream/libhdfs3/src/client/FileSystemInter.h:94:27: note: 	virtual Hdfs::Internal::EncryptionKey Hdfs::Internal::FileSystemInter::getEncryptionKeys()
     virtual EncryptionKey getEncryptionKeys() = 0;
                           ^~~~~~~~~~~~~~~~~
/home/alex/source/git/libhdfs3-downstream/libhdfs3/src/client/FileSystemInter.h:464:29: note: 	virtual Hdfs::Internal::SessionConfig& Hdfs::Internal::FileSystemInter::getConf()
     virtual SessionConfig & getConf() = 0;
                             ^~~~~~~
```

PR for those coming up. Is there CI infrastructure for libhdfs3?

Testing via hdfs3 is also a good idea, will do.

**Comment by martindurant** [comment]
Did all tests pass over at hdfs3?

**Comment by sk1p** [comment]
Sorry, didn't get to it yet

**Comment by sk1p** [comment]
Sadly I wasn't able to inject my own libhdfs3.so.* into the docker image, so I suspect there may be version differences. I get these two failures:

```
=========================================== FAILURES ===========================================
__________________________________ test_default_port_and_host __________________________________

no_conf = None

    def test_default_port_and_host(no_conf):
        guess_config()
        hdfs = HDFileSystem(connect=False)
>       assert hdfs.host == conf_defaults['host']
E       AssertionError: assert 'this.place' == 'localhost'
E         - this.place
E         + localhost

hdfs3/tests/test_conf.py:101: AssertionError
__________________________________________ test_chmod __________________________________________

hdfs = hdfs://localhost:8020, Connected

    def test_chmod(hdfs):
        hdfs.touch(a)
        assert hdfs.ls(a, True)[0]['permissions'] == 0o777
        hdfs.chmod(a, 0o500)
        assert hdfs.ls(a, True)[0]['permissions'] == 0o500
        hdfs.chmod(a, 0o100)
        with pytest.raises(IOError):
>           hdfs.open(a, 'ab')
E           Failed: DID NOT RAISE <class 'OSError'>

hdfs3/tests/test_hdfs3.py:805: Failed
================== 2 failed, 72 passed, 2 xfailed, 1 xpassed in 19.65 seconds ==================
```

The first is obviously because of configuration differences between the docker container and my local hdfs installation, the second looks unrelated to the patch. I'm testing with hadoop 3.1.0.

Good point about the intermediate variable, seems to work without it.

**Comment by sk1p** [comment]
I re-ran the tests (outside of docker) without my patch, and got the same two failures. So they are unrelated to my changes.

**Comment by martindurant** [comment]
Yep, those failures are ok. Indeed, the first is just about how configuration is done, and the second is because you must be accessing your HDFS container with root privileges (this is normal for docker, but not otherwise).

**Comment by martindurant** [comment]
So merging this!
I'll see you over on hdfs3 to actually use the new option.

**Pull request merged**
